---
- name: Run Clam repo trying.
  yum: 
    name: epel-release
    state: present
- name: Run Clam repo trying.
  yum:
    name: selinux-policy
    state: present

- name: Run Clam repo trying.
  yum:
    name: libselinux-python
    state: present

- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing
  notify:
    - "selinux enforced"

#- name: Reboot immediately if there was a change.
#  shell: "sleep 5 && reboot"
#  async: 1
#  poll: 0
#- name: Wait for the reboot to complete if there was a change.
#  wait_for_connection:
#    connect_timeout: 20
#    sleep: 5
#    delay: 5
#    timeout: 300
